const Agents = [
  {
    agentId: "C-87654321",
    agentName: "Alice Johnson",
    position: "Customer Support",
    status: "Active",
    avgScore: 92.5,
    callsHandled: 1280,
  },
  {
    agentId: "C-87654321",
    agentName: "Bob Williams",
    position: "Technical Support",
    status: "Active",
    avgScore: 88,
    callsHandled: 950,
  },
  {
    agentId: "C-87654321",
    agentName: "Charlie Brown",
    position: "Sales Representative",
    status: "Inactive",
    avgScore: 85,
    callsHandled: 720,
  },
  {
    agentId: "C-87654321",
    agentName: "Diana Prince",
    position: "Customer Support",
    status: "Active",
    avgScore: 95.1,
    callsHandled: 1500,
  },
  {
    agentId: "C-87654321",
    agentName: "Eve Adams",
    position: "Technical Support",
    status: "Active",
    avgScore: 90.7,
    callsHandled: 1100,
  },
  {
    agentId: "C-87654321",
    agentName: "Frank White",
    position: "Sales Representative",
    status: "Inactive",
    avgScore: 78.9,
    callsHandled: 600,
  },
  {
    agentId: "C-87654321",
    agentName: "Grace Kelly",
    position: "Customer Support",
    status: "Active",
    avgScore: 91,
    callsHandled: 1350,
  },
  {
    agentId: "C-87654321",
    agentName: "Henry Ford",
    position: "Technical Support",
    status: "Active",
    avgScore: 89.5,
    callsHandled: 1020,
  },
  {
    agentId: "C-87654321",
    agentName: "Ivy Green",
    position: "Customer Support",
    status: "Active",
    avgScore: 93.8,
    callsHandled: 1485,
  },
]

export default Agents